# Generated by Django 3.2.10 on 2022-01-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upassword',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
